Repository codesquad-issue-team-05/issue-tracker-max, pull requests merged in 2023-08, with the labels that each got.

#19 Dev be/feature/#15
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/global/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/GlobalExceptionHandler.java
  be/issue/src/main/java/codesquad/issueTracker/global/StatusCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/SuccessCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/config/WebConfig.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/CustomException.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/GlobalExceptionHandler.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/StatusCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/SuccessCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/AuthFilter.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/Jwt.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/JwtProperties.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/Token.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/dto/RequestRefreshTokenDto.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/service/JwtProvider.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/LoginType.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/User.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/LoginRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/LoginResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/SignUpRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/repository/UserRepository.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/test/java/annotation/RepositoryTest.java
  be/issue/src/test/java/annotation/ServiceTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/repository/UserRepositoryTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserServiceTest.java
Labels: ✨ feat, 💻 BE, 🧹 chore

#20 [BE] 로그아웃 API 구현
  .github/pull_request_template.md
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/AuthFilter.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/repository/UserRepository.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
Labels: 💻 BE, 🧹 chore

#22 [FE] 페이지 라우트
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/Components.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Main.tsx
  frontend/src/routes/AuthenticatedRoute.tsx
  frontend/src/types/ContextLogo.ts
Labels: ✨ feat, 🧑‍💻 FE

#23 [BE] OAuth 로그인 구현
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/global/config/OauthConfig.java
  be/issue/src/main/java/codesquad/issueTracker/global/config/WebConfig.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/AuthFilter.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/OAuthProperties.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/OauthAttributes.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/UserProfile.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/dto/OauthTokenResponse.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/InMemoryProviderRepository.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/JwtProvider.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/OauthAdapter.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/OauthProvider.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/LoginType.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/LoginRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/SignUpRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/repository/UserRepository.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserServiceTest.java
Labels: ✨ feat, 💻 BE, 🧹 chore

#28 Dev be/feature/#25
  be/issue/src/main/java/codesquad/issueTracker/comment/controller/CommentController.java
  be/issue/src/main/java/codesquad/issueTracker/comment/domain/Comment.java
  be/issue/src/main/java/codesquad/issueTracker/comment/repository/CommentRepository.java
  be/issue/src/main/java/codesquad/issueTracker/comment/service/CommentService.java
  be/issue/src/main/java/codesquad/issueTracker/global/config/OauthConfig.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/AuthFilter.java
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/Issue.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/OAuthProperties.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/domain/OauthAttributes.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/InMemoryProviderRepository.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/OauthAdapter.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/util/OauthProvider.java
  be/issue/src/main/java/codesquad/issueTracker/label/controller/LabelController.java
  be/issue/src/main/java/codesquad/issueTracker/label/domain/Label.java
  be/issue/src/main/java/codesquad/issueTracker/label/repository/LabelRepository.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/controller/MilestoneController.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/domain/Milestone.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/repository/MilestoneRepository.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/oauth/domain/OAuthProperties.java
  be/issue/src/main/java/codesquad/issueTracker/oauth/domain/OauthAttributes.java
  be/issue/src/main/java/codesquad/issueTracker/oauth/service/OAuthService.java
  be/issue/src/main/java/codesquad/issueTracker/oauth/util/OauthAdapter.java
  be/issue/src/main/java/codesquad/issueTracker/oauth/util/OauthProvider.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/User.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserValidator.java
  be/issue/src/test/java/codesquad/issueTracker/user/controller/UserControllerTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserServiceTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserValidatorTest.java
Labels: ♻️ refactor, 💻 BE, 🧹 chore

#48 [FE] GitHub OAuth 기능 추가
  frontend/src/App.tsx
  frontend/src/context/AuthProvider.tsx
  frontend/src/hooks/useRefreshToken.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/GitHubCallback.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Main.tsx
  frontend/vite.config.ts
Labels: ✨ feat, 🧑‍💻 FE

#54 [BE] 마일스톤 추가,수정,삭제,상태변경,상태 별 조회 API
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/GlobalExceptionHandler.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/StatusFilter.java
  be/issue/src/main/java/codesquad/issueTracker/jwt/dto/ResponseAccessToken.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/controller/MilestoneController.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/domain/Milestone.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/dto/MileStoneStatusDto.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/dto/MilestoneResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/dto/ModifyMilestoneRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/repository/MilestoneRepository.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneValidator.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/vo/MilestoneVo.java
Labels: ✨ feat, 💻 BE

#51 [BE] 댓글 관련 crud 구현
  .idea/.gitignore
  be/issue/src/main/java/codesquad/issueTracker/comment/controller/CommentController.java
  be/issue/src/main/java/codesquad/issueTracker/comment/domain/Comment.java
  be/issue/src/main/java/codesquad/issueTracker/comment/dto/CommentRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/comment/dto/CommentResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/comment/repository/CommentRepository.java
  be/issue/src/main/java/codesquad/issueTracker/comment/service/CommentService.java
  be/issue/src/main/java/codesquad/issueTracker/comment/vo/CommentUser.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/User.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/SignUpRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserValidator.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserServiceTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserValidatorTest.java
Labels: ✨ feat, 💻 BE

#68 [FE] FE 3주차 작업 PR
  .gitignore
  frontend/.env
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/asset/icons/check_box/active.svg
  frontend/src/asset/icons/check_box/disable.svg
  frontend/src/asset/icons/check_box/initial.svg
  frontend/src/asset/icons/label.svg
  frontend/src/asset/icons/milestone.svg
  frontend/src/components/BaseButton.tsx
  frontend/src/components/ButtonLarge.tsx
  frontend/src/components/ButtonSmall.tsx
  frontend/src/components/IssueTable.tsx
  frontend/src/components/LabelList.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/common/CommentElements.tsx
  frontend/src/components/common/DropdownPanel.tsx
  frontend/src/components/common/TabButton.tsx
  frontend/src/components/common/TextInput.tsx
  frontend/src/components/common/button/BaseButton.tsx
  frontend/src/components/common/button/ButtonLarge.tsx
  frontend/src/components/common/button/ButtonSmall.tsx
  frontend/src/components/landmark/Header.tsx
  frontend/src/components/landmark/Main.tsx
  frontend/src/components/landmark/Toolbar.tsx
  frontend/src/constant/CheckBox.tsx
  frontend/src/context/AuthProvider.tsx
  frontend/src/design/Icons.ts
  frontend/src/hooks/useRefreshToken.ts
  frontend/src/main.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Components.tsx
  frontend/src/pages/GitHubCallback.tsx
  frontend/src/pages/Issues.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/Options.tsx
  frontend/vite.config.ts
Labels: 🧑‍💻 FE

#69 #66 style : 코드스타일 , 패키지,클래스 구조 통일, 불필요한 주석제거 ,자동줄바꿈 적용
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/comment/controller/CommentController.java
  be/issue/src/main/java/codesquad/issueTracker/comment/dto/CommentResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/comment/repository/CommentRepository.java
  be/issue/src/main/java/codesquad/issueTracker/comment/vo/CommentUser.java
  be/issue/src/main/java/codesquad/issueTracker/comment/vo/CommentUserVo.java
  be/issue/src/main/java/codesquad/issueTracker/global/ApiResponse.java
  be/issue/src/main/java/codesquad/issueTracker/global/common/ApiResponse.java
  be/issue/src/main/java/codesquad/issueTracker/global/common/Status.java
  be/issue/src/main/java/codesquad/issueTracker/global/config/CorsConfig.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/GlobalExceptionHandler.java
  be/issue/src/main/java/codesquad/issueTracker/global/filter/AuthFilter.java
  be/issue/src/main/java/codesquad/issueTracker/label/controller/LabelController.java
  be/issue/src/main/java/codesquad/issueTracker/label/controller/dto/LabelResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/label/domain/Label.java
  be/issue/src/main/java/codesquad/issueTracker/label/dto/CreateLabelResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/label/dto/LabelRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/label/dto/LabelResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/label/repository/LabelRepository.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/label/vo/LabelVo.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/controller/MilestoneController.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/user/controller/UserController.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/LoginRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/user/dto/SignUpRequestDto.java
Labels: 💻 BE, 🧹 chore

#77 [BE] 마일스톤 테스트 코드 구현
  be/issue/src/main/java/codesquad/issueTracker/milestone/dto/MileStoneStatusDto.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/dto/ModifyMilestoneRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneValidator.java
  be/issue/src/test/java/annotation/ControllerTest.java
  be/issue/src/test/java/annotation/IntegrationTest.java
  be/issue/src/test/java/annotation/RepositoryTest.java
  be/issue/src/test/java/codesquad/issueTracker/milestone/controller/MilestoneControllerTest.java
  be/issue/src/test/java/codesquad/issueTracker/milestone/intergration/MilestoneIntegrationTest.java
  be/issue/src/test/java/codesquad/issueTracker/milestone/repository/MilestoneRepositoryTest.java
  be/issue/src/test/java/codesquad/issueTracker/milestone/service/MilestoneServiceTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/controller/UserControllerTest.java
  be/issue/src/test/java/codesquad/issueTracker/user/service/UserValidatorTest.java
  be/issue/src/test/resources/data.sql
  be/issue/src/test/resources/schema.sql
Labels: 🛠️ fix, ♻️ refactor, 💻 BE

#81 [BE] 댓글 테스트 코드 구현
  be/issue/src/main/java/codesquad/issueTracker/comment/controller/CommentController.java
  be/issue/src/main/java/codesquad/issueTracker/comment/dto/CommentRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/comment/service/CommentService.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/test/java/codesquad/issueTracker/comment/controller/CommentControllerTest.java
  be/issue/src/test/java/codesquad/issueTracker/comment/fixture/CommentTestFixture.java
  be/issue/src/test/java/codesquad/issueTracker/comment/repository/CommentRepositoryTest.java
  be/issue/src/test/java/codesquad/issueTracker/comment/service/CommentServiceTest.java
Labels: 🛠️ fix, ♻️ refactor, 💻 BE

#82 [be] 이슈 작성 api 구현 ,통합테스트 , 레포지토리 테스트 완료
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/Issue.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueWriteRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/label/repository/LabelRepository.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/user/repository/UserRepository.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
  be/issue/src/test/java/codesquad/issueTracker/issue/Integration/IssueIntegrationTest.java
  be/issue/src/test/java/codesquad/issueTracker/issue/repository/IssueRepositoryTest.java
  be/issue/src/test/java/codesquad/issueTracker/milestone/intergration/MilestoneIntegrationTest.java
  be/issue/src/test/resources/data.sql
Labels: ✨ feat, 💻 BE

#91 [be] 이슈 수정, 이슈상태 수정,이슈 옵션 수정
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyAssigneeRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueContentRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueContentResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueMilestoneDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueStatusRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueTitleRequest.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyIssueTitleResponse.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/ModifyLabelRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/label/repository/LabelRepository.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
Labels: ✨ feat, 💻 BE

#89 [BE] 이슈 조회 API 구현(이슈 목록 조회 API 제외)
  be/issue/src/main/java/codesquad/issueTracker/comment/repository/CommentRepository.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueLabelResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueMilestoneResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueOptionResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueUserResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/AssigneeVo.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueLabelVo.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueMilestoneVo.java
  be/issue/src/main/java/codesquad/issueTracker/label/repository/LabelRepository.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/label/vo/LabelVo.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/repository/MilestoneRepository.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
  be/issue/src/main/java/codesquad/issueTracker/user/repository/UserRepository.java
  be/issue/src/main/java/codesquad/issueTracker/user/service/UserService.java
Labels: ✨ feat, 💻 BE, 🧹 chore

#88 [FE] 이슈작성 페이지 레이아웃 작업 PR
  frontend/src/App.tsx
  frontend/src/asset/images/defaultUserImg.png
  frontend/src/components/Layout.tsx
  frontend/src/components/common/TextArea.tsx
  frontend/src/components/common/TextInput.tsx
  frontend/src/components/landmark/Main.tsx
  frontend/src/design/Icons.ts
  frontend/src/pages/AddIssue.tsx
Labels: ✨ feat, 🧑‍💻 FE

#94 #93 feat : 파일 업로드 api 구현, 예외처리 완료
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/global/exception/ErrorCode.java
  be/issue/src/main/java/codesquad/issueTracker/global/exception/GlobalExceptionHandler.java
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueFileResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
Labels: ✨ feat, 💻 BE

#95 [BE] 이슈 라벨, 마일스톤, 참여자 목록 조회 응답 형식 변경
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueLabelResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueMilestoneResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueOptionResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueUserResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueLabelVo.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueMileStoneDetailVo.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueMilestoneVo.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueUserVo.java
  be/issue/src/main/java/codesquad/issueTracker/label/service/LabelService.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/repository/MilestoneRepository.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/service/MilestoneService.java
Labels: ♻️ refactor, 💻 BE

#98 #96 feat : 이슈 목록 필터링 및 조회
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/Issue.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/IssueRead.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/IssueSearch.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueCountResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueFilterRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/IssueFilteredResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/LabelDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/MilestoneDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/UserDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueMapperRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueFilteredVo.java
  be/issue/src/main/java/codesquad/issueTracker/label/domain/Label.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/domain/Milestone.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/User.java
  be/issue/src/main/resources/mapper/IssueMapper.xml
Labels: ✨ feat, 💻 BE

#100 [be] 이슈목록 조회 및 필터링
  be/issue/build.gradle
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/Issue.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/IssueRead.java
  be/issue/src/main/java/codesquad/issueTracker/issue/domain/IssueSearch.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueCountResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/IssueFilterRequestDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/IssueFilteredResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/LabelDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/MilestoneDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/dto/filter/UserDetailResponseDto.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueMapperRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/repository/IssueRepository.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
  be/issue/src/main/java/codesquad/issueTracker/issue/vo/IssueFilteredVo.java
  be/issue/src/main/java/codesquad/issueTracker/label/domain/Label.java
  be/issue/src/main/java/codesquad/issueTracker/milestone/domain/Milestone.java
  be/issue/src/main/java/codesquad/issueTracker/user/domain/User.java
  be/issue/src/main/resources/mapper/IssueMapper.xml
Labels: ✨ feat, 💻 BE

#103 [be] 마일스톤 null 처리 수정 , 이슈 목록조회 상태 디폴트 값 open 으로 지정
  be/issue/src/main/java/codesquad/issueTracker/issue/controller/IssueController.java
  be/issue/src/main/java/codesquad/issueTracker/issue/service/IssueService.java
Labels: 🛠️ fix, 💻 BE

#112 [FE] 이슈작성/상세페이지 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/common/TextArea.tsx
  frontend/src/components/common/button/BaseButton.tsx
  frontend/src/pages/AddIssue.tsx
  frontend/src/pages/Components.tsx
  frontend/src/pages/IssueDetail.tsx
  frontend/src/pages/Issues.tsx
  frontend/src/pages/Register.tsx
Labels: ✨ feat, 🧑‍💻 FE
